---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui
  name: kubeslice-ui
  namespace: kubeslice-controller
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: ui
  type: {{ .Values.kubeslice.ui.service.type }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeslice-ui
  namespace: kubeslice-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - image: '{{ .Values.kubeslice.ui.image }}:{{ .Values.kubeslice.ui.tag }}'
        imagePullPolicy: '{{ .Values.kubeslice.ui.pullPolicy }}'
        name: ui
        ports:
        - containerPort: 3000
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}