apiVersion: v1
entries:
  busybox:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-04-20T17:38:17.563113+05:30"
    description: A Helm chart for Kubernetes
    digest: 747ba46be7471faffbf0a8065aa6d391f29fb9171ccf9f6c62849356fcde49d7
    name: busybox
    type: application
    urls:
    - busybox-0.1.0.tgz
    version: 0.1.0
  nginx:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-04-20T17:38:17.564786+05:30"
    description: A Helm chart for Kubernetes
    digest: a92b13eb9339e77e01a8ea0afb3ff8a51773da12f4a73f36e96fdee3ee78b108
    name: nginx
    type: application
    urls:
    - nginx-0.1.0.tgz
    version: 0.1.0
  postgres:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-04-20T17:38:17.5658+05:30"
    description: A Helm chart for Kubernetes
    digest: b0ae200756be96ea9f19216de4b3af395283278137964508678f6f4b9578b7a6
    name: postgres
    type: application
    urls:
    - postgres-0.1.0.tgz
    version: 0.1.0
generated: "2022-04-20T17:38:17.560988+05:30"
