kubeslice:
  ui:
    image: aveshadev/kubeslice-ui-ent
    tag: 1.14.0-SNAPSHOT-c28bcbc1
    pullPolicy: IfNotPresent
    service:
      type: LoadBalancer
  rbacproxy:
    image: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.8.0
  controller:
    logLevel: info
    rbacResourcePrefix: kubeslice-rbac
    projectnsPrefix: kubeslice
    endpoint: 
    image: aveshasystems/kubeslice-controller
    tag: 0.3.6
    pullPolicy: IfNotPresent
  ovpnJob:
    image: aveshasystems/gateway-certs-generator
    tag: 0.1.1

imagePullSecrets:
- name: kubeslice-ui-ent-dev-creds
